{"trial_id": "01", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "num_conv_layers", "default": null, "conditions": [], "min_value": 1, "max_value": 10, "step": 1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "kernel_size_0", "default": null, "conditions": [], "min_value": 3, "max_value": 8, "step": 1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "filters_0", "default": null, "conditions": [], "min_value": 32, "max_value": 256, "step": 32, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "kernel_size_1", "default": null, "conditions": [], "min_value": 3, "max_value": 3, "step": 1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "filters_1", "default": null, "conditions": [], "min_value": 32, "max_value": 256, "step": 32, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "kernel_size_2", "default": null, "conditions": [], "min_value": 1, "max_value": 1, "step": 1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "filters_2", "default": null, "conditions": [], "min_value": 32, "max_value": 256, "step": 32, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "kernel_size_3", "default": null, "conditions": [], "min_value": 1, "max_value": 1, "step": 1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "filters_3", "default": null, "conditions": [], "min_value": 32, "max_value": 256, "step": 32, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "kernel_size_4", "default": null, "conditions": [], "min_value": 1, "max_value": 1, "step": 1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "filters_4", "default": null, "conditions": [], "min_value": 32, "max_value": 256, "step": 32, "sampling": "linear"}}], "values": {"num_conv_layers": 3, "kernel_size_0": 3, "filters_0": 32, "kernel_size_1": 3, "filters_1": 256, "kernel_size_2": 1, "filters_2": 224, "kernel_size_3": 1, "filters_3": 160, "kernel_size_4": 1, "filters_4": 32}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"C:\\Users\\jaime\\Desktop\\Trabajo\\IRNAS\\.venv\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"C:\\Users\\jaime\\Desktop\\Trabajo\\IRNAS\\.venv\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"C:\\Users\\jaime\\Desktop\\Trabajo\\IRNAS\\.venv\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"C:\\Users\\jaime\\Desktop\\Trabajo\\IRNAS\\.venv\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n  File \"C:\\Users\\jaime\\Desktop\\Trabajo\\IRNAS\\.venv\\lib\\site-packages\\keras_tuner\\src\\engine\\hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n  File \"C:\\Users\\jaime\\Desktop\\Trabajo\\IRNAS\\.venv\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 122, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"C:\\Users\\jaime\\Desktop\\Trabajo\\IRNAS\\.venv\\lib\\site-packages\\tensorflow\\python\\eager\\execute.py\", line 53, in quick_execute\n    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:\n\nDetected at node compile_loss/sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits defined at (most recent call last):\n  File \"c:\\Users\\jaime\\Desktop\\Trabajo\\IRNAS\\classifying\\ClassifiersFullAnalysisCNNmixedData.py\", line 341, in <module>\n\n  File \"C:\\Users\\jaime\\Desktop\\Trabajo\\IRNAS\\.venv\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 234, in search\n\n  File \"C:\\Users\\jaime\\Desktop\\Trabajo\\IRNAS\\.venv\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 274, in _try_run_and_update_trial\n\n  File \"C:\\Users\\jaime\\Desktop\\Trabajo\\IRNAS\\.venv\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 239, in _run_and_update_trial\n\n  File \"C:\\Users\\jaime\\Desktop\\Trabajo\\IRNAS\\.venv\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 314, in run_trial\n\n  File \"C:\\Users\\jaime\\Desktop\\Trabajo\\IRNAS\\.venv\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 233, in _build_and_fit_model\n\n  File \"C:\\Users\\jaime\\Desktop\\Trabajo\\IRNAS\\.venv\\lib\\site-packages\\keras_tuner\\src\\engine\\hypermodel.py\", line 149, in fit\n\n  File \"C:\\Users\\jaime\\Desktop\\Trabajo\\IRNAS\\.venv\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 117, in error_handler\n\n  File \"C:\\Users\\jaime\\Desktop\\Trabajo\\IRNAS\\.venv\\lib\\site-packages\\keras\\src\\backend\\tensorflow\\trainer.py\", line 318, in fit\n\n  File \"C:\\Users\\jaime\\Desktop\\Trabajo\\IRNAS\\.venv\\lib\\site-packages\\keras\\src\\backend\\tensorflow\\trainer.py\", line 121, in one_step_on_iterator\n\n  File \"C:\\Users\\jaime\\Desktop\\Trabajo\\IRNAS\\.venv\\lib\\site-packages\\keras\\src\\backend\\tensorflow\\trainer.py\", line 108, in one_step_on_data\n\n  File \"C:\\Users\\jaime\\Desktop\\Trabajo\\IRNAS\\.venv\\lib\\site-packages\\keras\\src\\backend\\tensorflow\\trainer.py\", line 54, in train_step\n\n  File \"C:\\Users\\jaime\\Desktop\\Trabajo\\IRNAS\\.venv\\lib\\site-packages\\keras\\src\\trainers\\trainer.py\", line 357, in _compute_loss\n\n  File \"C:\\Users\\jaime\\Desktop\\Trabajo\\IRNAS\\.venv\\lib\\site-packages\\keras\\src\\trainers\\trainer.py\", line 325, in compute_loss\n\n  File \"C:\\Users\\jaime\\Desktop\\Trabajo\\IRNAS\\.venv\\lib\\site-packages\\keras\\src\\trainers\\compile_utils.py\", line 609, in __call__\n\n  File \"C:\\Users\\jaime\\Desktop\\Trabajo\\IRNAS\\.venv\\lib\\site-packages\\keras\\src\\trainers\\compile_utils.py\", line 645, in call\n\n  File \"C:\\Users\\jaime\\Desktop\\Trabajo\\IRNAS\\.venv\\lib\\site-packages\\keras\\src\\losses\\loss.py\", line 43, in __call__\n\n  File \"C:\\Users\\jaime\\Desktop\\Trabajo\\IRNAS\\.venv\\lib\\site-packages\\keras\\src\\losses\\losses.py\", line 27, in call\n\n  File \"C:\\Users\\jaime\\Desktop\\Trabajo\\IRNAS\\.venv\\lib\\site-packages\\keras\\src\\losses\\losses.py\", line 1853, in sparse_categorical_crossentropy\n\n  File \"C:\\Users\\jaime\\Desktop\\Trabajo\\IRNAS\\.venv\\lib\\site-packages\\keras\\src\\ops\\nn.py\", line 1567, in sparse_categorical_crossentropy\n\n  File \"C:\\Users\\jaime\\Desktop\\Trabajo\\IRNAS\\.venv\\lib\\site-packages\\keras\\src\\backend\\tensorflow\\nn.py\", line 645, in sparse_categorical_crossentropy\n\nReceived a label value of 2 which is outside the valid range of [0, 2).  Label values: 1 2 2 1 1 1 2 2 1 1 2 1 1 1 1 1 1 2 1 1 1 1 2 1 2 1 1 1 2 1 2 2\n\t [[{{node compile_loss/sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]] [Op:__inference_one_step_on_iterator_4384]\n"}